### ISSUE TITLE
Regarding the error in SHARC/diagnostics.py

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#123]
Dear Sir,
I am trying to run SHARC/diagnostics.py command after the successfully of trajectories run but I got an error like this 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Singlet_2/TRAJ_00120 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Output files:     .lis .. .log .. .dat .. .xyz .. OK
    Restart files:    ctrl .. traj .. restart/ ..     OK
    Progress:         [=========================]     1000.0 of 1000.0 fs
    Status:                                           FINISHED
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1232, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1223, in main
    INFOS = do_calc(INFOS)
  File "/home/mhgroup1/kumar/sharc/bin/diagnostics.py", line 1062, in do_calc
    lis[float(x[0])] = x[1:]
ValueError: could not convert string to float: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
 



Could you please assist me in resolving this issue at your earliest convenience?

Looking forward to your guidance.

Best regards,
LUKHMANUL HAKEEM K.

**Comment by maisebastian** [comment]
Dear lukhman9020,
this sounds like one of your files was corrupted somehow. Please check the output.lis file of the corresponding trajectory (the trajectory number is not in your error print out, so I cannot tell you. 

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear lukhman9020, this sounds like one of your files was corrupted somehow. Please check the output.lis file of the corresponding trajectory (the trajectory number is not in your error print out, so I cannot tell you.
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply. Now I rerun the trajectory, which has crashed, and solved the problem.

Best regards,
LUKHMANUL HAKEEM K.
