### ISSUE TITLE
Error using theodor

### ISSUE THREAD

**Issue by jakobcasa** [sharc-md/sharc#125]
Dear all

I tried to use Theodor with SHARC, and with this, I have one question and one error to report:
Question: Is it possible to use Theodore with LVC? As far as I understand, it is not possible in the NetCDF, but I am not sure when I used to print out the output normally (I know it is slower).

Error:

I am calculating the ICOND_00000, and the following error occurs:

 Traceback (most recent call last):
  File "/storage/homefs/jc22p286/applications/sharc/bin/SHARC_ORCA.py", line 5289, in <module>
    main()
  File "/storage/homefs/jc22p286/applications/sharc/bin/SHARC_ORCA.py", line 5244, in main
    QMin = readQMin(QMinfilename)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/jc22p286/applications/sharc/bin/SHARC_ORCA.py", line 2146, in readQMin
    QMin['theodir'] = get_sh2Orca_environ(sh2Orca, 'theodir', False, False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/jc22p286/applications/sharc/bin/SHARC_ORCA.py", line 1720, in get_sh2Orca_environ
    LINE = line[1]
           ~~~~^^^
IndexError: list index out of range

Is there an easy fix for this? If you want to have a look at the folder, I'm happy to share it with you

Thank you, have a nice evening

Best Jakob

**Comment by maisebastian** [comment]
Hi Jakob,
in SHARC 3, it is not possible to use TheoDORE with LVC. This is because it is somewhat complicated to do a basis transformation with the TheoDORE descriptors (e.g., from the diabatic parametrization basis to the current adiabatic basis). This might be a future feature, though. 

About your error message, this appears to be a problem in getting the environment variable for $THEODIR. I recommend to explicitly add the path to the ORCA.resource file as `theodir /your/path/to/theodore` or `theodir $THEODIR` if you source TheoDORE's setpaths.bash before starting SHARC.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Thank you for the information. Concerning the error  I did this already here is the ORCA.reasources

orcadir /software.9/software/ORCA/5.0.3-gompi-2021b/bin/
scratchdir ./SCR/ICOND_00000//
ncpu 16
schedule_scaling 0.800000
memory 4000
wfoverlap $SHARC/wfoverlap.x
wfthres 0.998000
theodir  /storage/homefs/jc22p286/TheoDORE/TheoDORE_3.1.1
theodore_prop ['Om', 'PRNTO', 'S_HE', 'Z_HE', 'RMSeh']
theodore_fragment []

But when I use $THEODIR the following Theodor error appears: Traceback (most recent call last):
  File "/storage/homefs/jc22p286/TheoDORE/TheoDORE_3.1.1/bin/analyze_tden.py", line 3, in <module>
    from .theotools import timeit
ImportError: attempted relative import with no known parent package, which tells me that the path is not quite correctly set, but when I do $THEODIR it shows me the same directory as above, also when I do Theodore -h in the terminal it does give my:
================================================================================
|                                TheoDORE 3.1.1                                |
|         Theoretical Density, Orbital Relaxation and Exciton analysis         |
|                                                                              |
|                            Author: Felix Plasser                             |
|             Contributions by: L. Stojanovic, G. Hermann, S. Mai,             |
|                          M.F.S.J. Menger, P. Kimber                          |
--------------------------------------------------------------------------------
|                       References for the modules used                        |
|        (see also http://theodore-qc.sourceforge.net/literature.html)         |
|                                                                              |
|   Program citation:                                                          |
|     F. Plasser, J. Chem. Phys. (2020), 152, 084108.                          |
================================================================================

 So, I am assuming that it works fine, I also loaded the same modules in the submission script

Best Jakob

**Comment by maisebastian** [comment]
I am not sure right now whether TheoDORE 3 will correctly work with SHARC. This is because in TheoDORE 3, all program features are called through `theodore something` rather than calling `something.py` itself. You might want to try to change the hardcoded call to `analyze_tden.py` at https://github.com/sharc-md/sharc/blob/3141f685b39c2546877859717035755b44387a73/bin/SHARC_ORCA.py#L4226 to the correct call. If that works, we can adapt the code to automatically detect the TheoDORE version and the calls in affected interfaces.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Well, the file analyze_tden.py is in Theodore 3 in the following folder TheoDORE/TheoDORE_3.1.1/theodore/actions/

But what I did initially is just copying the "analyze_tden.py" into the bin directory since the, from there the import .action ... is working fine, instead of changing the path

I don't know if this helps. 
Which version was the last one that worked fine?  Then I will download this one!

Best Jakob

**Comment by maisebastian** [comment]
Any TheoDORE 2.X should work with our interfaces. So I suggest you try the 2.4 that is on github.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Thank you
best, have a nice weekend

Jakob

**Comment by felixplasser** [comment]
Withing TheoDORE 3, you'll have to do something like

`string = 'theodore analyze_tden'`

The file `analyze_tden.py` is not an executable.

**Comment by maisebastian** [comment]
Hi Felix, thanks a lot! Does "everything else" (e.g., dens_ana.in, output formatting) stay consistent between TheoDORE 2 and 3? And is there a robust way to look up the TheoDORE version? If yes and yes, then the SHARC interfaces could be super easily adjusted to TheoDORE 3. 

Best,
Sebastian

**Comment by felixplasser** [comment]
Hi Sebastian,

yes, the remaining output is the same as before. So, this should be all compatible.

Maybe the easiest way is to check if the file `$THEODIR/bin/theodore` exists. If so, then one should call this. Everything else can stay the same.

Cheers
Felix

**Comment by maisebastian** [comment]
Hmm, after incorporating this into SHARC_ORCA.py, I was reminded that in TheoDORE 3 and ORCA 5, cclib gives problems if one has SOCs active. Therefore, I would change it such that SHARC_ORCA.py only works with TheoDORE 3 with the "orca" readtype. Is this already in the main branch of TheoDORE?

**Comment by felixplasser** [comment]
Hi Sebastian,
I recently released Version 3.2
https://github.com/felixplasser/theodore-qc/releases/
This has the standalone Orca interface, which is more stable and runs with SOC.

I had another chat with @jakobcasa , and I think it worked for him.

**Comment by maisebastian** [comment]
Hi Felix,
thanks for confirming (and for the nice work in TheoDORE :) ). I have now pushed a commit to SHARC's main branch, where SHARC_ORCA.py can use TheoDORE 3. If one uses TheoDORE 3, but gets an error, it prints an error message saying that one should use at least 3.2.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear all

Yes it did work, but only upon changing the line 4193 and the following in the SHARC_ORCA.py to:

     inputstring = '''rtype='orca'
mo_file='ORCA.molden.input'
rfile='ORCA.log'
read_binary=True
jmol_orbitals=False
molden_orbitals=False
Om_formula=2
eh_pop=1
comp_ntos=True
print_OmFrag=True
output_file='tden_summ.txt'
prop_list=%s
at_lists=%s
''' % (str(QMin['template']['theodore_prop']), str(QMin['template']['theodore_fragment']))

Best
Jakob

**Comment by maisebastian** [comment]
Hi Jakob,
this is exactly what the new commit does in SHARC_ORCA.py. If it detects TheoDORE >=3 (by looking for $THEODIR/bin/theodore), then it will write rtype=orca and add the mo_file keyword. Otherwise, it uses what it used to do before.

That should now work for TheoDORE 2.x and TheDORE >=3.2, but not for TheoDORE 3.0-3.1, because of the problems it has with cclib and SOCs.

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Sorry to bother you again, but unfortunately, I have issues analyzing the Theodore data with a finished SHARC TRAJ; I could not find a .gbw file to produce a molden file to proceed. The only one I was able to see is the initial gbw. 

Thank you

Best
Jakob

**Comment by maisebastian** [comment]
Dear Jakob, 
SHARC does not store all the gbw files of all time steps, that would be a whole lot of data, especially for a full swarm. Therefore, what SHARC does is to run TheoDORE as part of the QC calculation of the time step, collect the data, and store it in output.dat. So you do not need to run TheoDORE after a trajectory is finished. 

To make this work, you have to:
- tell setup_traj.py that you want to use TheoDORE
- tell it later your fragments and descriptors
- check that the "input" file has the theodore keyword and some n_property1d set
- after the trajectory is finished, write some script that extracts the descriptors from the output.dat and write some file with per-time-step data that you can then gather with data_collector.py

Best,
Sebastian

**Comment by jakobcasa** [comment]
Dear Sebastian

Thank you for the fast reply! 
What structure does the file  data_collector.py need to have so that it can be read by it? Or maybe I misunderstood

Thanks for the feedback.

Best Jakob

**Comment by maisebastian** [comment]
data_collector.py expects that in every TRAJ_ folder is a file of the same name/path that has one line per time step, with the current time in one column (typically column 1) and then arbitrary data in other columns (e.g., bond lengths, energies, populations, theodore descriptors, ..., it is really fully flexible). Please have a look at https://sharc-md.org/?page_id=50#tth_sEc7.25 for more information. It can compute averages, standard deviations, Gaussian convolutions, ... It is SHARC's multi-purpose time-series analysis tool.
