### ISSUE TITLE
Error within SHARC_GAUSSIAN.py when running dynamics [UnboundLocalError: local variable 'eigenvectors_array' referenced before assignment]

### ISSUE THREAD

**Issue by Uranium92238** [sharc-md/sharc#149]
I was trying to run a `1000 fs` dynamics using the SHARC_GAUSSIAN interface. The initial steps and the start of the trajectory went as expected, without any errors. However, I noticed that the dynamics exited with a non-zero error code after running for some time as :

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<============================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  Entering timestep    292  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<  Trajectory time in fs   146.00000  >>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<============================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                                                        Start time: Thu Sep 19 23:51:49 2024

 =============================================================
 QM call was not successful, aborting the run.
 Error code:          256
 =============================================================
Total wallclock time:    0 days    3 h   25 min   34 sec
 ------------------------------------------------------------------------------------------
 SHARC fun fact #42: SHARC is not the ultimate answer to life and everything :(
 ------------------------------------------------------------------------------------------

```
A quick look into the QM.err file tells me

```
Traceback (most recent call last):
  File "/home/apogean/software/sharc-3.0.2/bin/SHARC_GAUSSIAN.py", line 4180, in <module>
    main()
  File "/home/apogean/software/sharc-3.0.2/bin/SHARC_GAUSSIAN.py", line 4144, in main
    errorcodes = runjobs(schedule, QMin)
  File "/home/apogean/software/sharc-3.0.2/bin/SHARC_GAUSSIAN.py", line 2240, in runjobs
    saveFiles(WORKDIR, jobset[job])
  File "/home/apogean/software/sharc-3.0.2/bin/SHARC_GAUSSIAN.py", line 2625, in saveFiles
    strings = get_dets_from_chk(f, QMin)
  File "/home/apogean/software/sharc-3.0.2/bin/SHARC_GAUSSIAN.py", line 2852, in get_dets_from_chk
    eig = [i for i in eigenvectors_array[startindex:endindex]]
UnboundLocalError: local variable 'eigenvectors_array' referenced before assignment
```
This looks like some problem with the way the python code is written rather than a problem with the way I am using the interfaces. To add to my point, I also do not understand that why this error did not happen for the first 291 time-steps, as the dynamics had run perfectly till then. I am using `Python 3.10.12` and the manual states that the release SHARC 3.0.x has been tested against Python 3.10 so this shouldn't be a problem arising from the version of Python I am using. Please let me know what I can do to make sure this does not happen in the future - I am guessing I would need to modify the source code files.

**Comment by Uranium92238** [comment]
Turns out the problem was with the Gaussian part of the calculation - the Gaussian.com was terminating without converging, the SHARC_GAUSSIAN.py was not able to detect the problem and hence was giving unhelpful error messages. As described in the manual, such a problem has to be fixed by reconsidering the level of theory being used.
