### ISSUE TITLE
Trying to run ORCA_THEODORE test, encountering error

### ISSUE THREAD

**Issue by maleylab** [sharc-md/sharc#152]
I am trying to run the ORCA_THEODORE test and keep running into the following error after the ORCA calculation completes. The following traceback is printing in the QM.err file:

`Traceback (most recent call last):
  File "/home/smaley/projects/def-smaley/smaley/sharc-3.0.2/bin/SHARC_ORCA.py", line 5282, in <module>
    main()
  File "/home/smaley/projects/def-smaley/smaley/sharc-3.0.2/bin/SHARC_ORCA.py", line 5246, in main
    errorcodes = runjobs(schedule, QMin)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smaley/projects/def-smaley/smaley/sharc-3.0.2/bin/SHARC_ORCA.py", line 2888, in runjobs
    saveFiles(WORKDIR, jobset[job])
  File "/home/smaley/projects/def-smaley/smaley/sharc-3.0.2/bin/SHARC_ORCA.py", line 3404, in saveFiles
    string = get_MO_from_gbw(f, QMin)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smaley/projects/def-smaley/smaley/sharc-3.0.2/bin/SHARC_ORCA.py", line 3476, in get_MO_from_gbw
    NAO = int(float(line.split()[0])) + 1
              ^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '[file'`

I am using ORCA 4.2.1 and TheoDORE 3.2.

Thanks!

**Comment by maisebastian** [comment]
Dear maleylab,
thanks for the report. The error message sounds at first glance like it is unrelated to TheoDORE, as it happened in the code that reads the MO coefficients from the gbw file. But it is difficult to trace the problem.

I tried to reproduce the error with the current main branch (not the SHARC 3.0.2 release). With ORCA 4.2.1, I get an error in ORCA which reads "CIS gradient runs using the RI approximation require a /C basis!" (I think this is a bug). If I add such a basis to the ORCA.template via, e.g., "keys def2-svp/C", the test runs through.

With ORCA 5.0.4 and TheoDORE 3.2 and using the current main branch, the ORCA_THEODORE test finishes successfully for me. Hence, I suggest that you use the current main branch (https://github.com/sharc-md/sharc/tree/main) and ORCA 5. If you really need to use ORCA 4.2.1 for some reason, you will need to add the /C basis. 

Please tell me if your original error persists with the main branch.

Best,
Sebastian

**Comment by maleylab** [comment]
Thank you! 

I was able to run the test successfully this morning using the main branch.

Out of curiosity, do you have any plans to update the code so it is compatible with ORCA 6?

Best,
Steven

**Comment by maisebastian** [comment]
This will most likely not happen anymore in SHARC 3. We are currently working in high gear on SHARC 4, which has a completely new interface infrastructure. The new SHARC_ORCA.py will be compatible with ORCA 6. 

If you really need an ORCA 6 interface quickly, we can probably make a quick, inofficial modification of the interface for you.

Best,
Sebastian

**Comment by maisebastian** [comment]
OK, it seemed to be not too complicated. In the main branch, you can find a version of SHARC_ORCA.py that should work with ORCA 6. However, this version does not correctly extracts static state dipole moments.

**Comment by maleylab** [comment]
Thanks Sebastian, it's working properly and appears to be much quicker when I run the same system/settings in ORCA 6.
