### ISSUE TITLE
Studying Excited State Dynamics in Different pH Environments

### ISSUE THREAD

**Issue by lukhman9020** [sharc-md/sharc#163]
Dear Sir,

I hope this message finds you well. I am planning to study the excited state dynamics of a system in three different pH environments. For this, I was thinking of preparing the initial sampling using the AMBER CpHMD (Constant pH Molecular Dynamics) method.
For the excited state dynamics study, I am considering running QM/MM simulations with SHARC, MOLCAS, and TINKER, using the SA-CASSCF (State-averaged Complete Active Space Self-Consistent Field) method for the quantum mechanical part of the calculations.
I would like to know if this approach is correct or if there is anything else I should consider to properly account for the pH differences during the excited state calculations.
Looking forward to hearing from you.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear Lukhmanul,
sounds like an interesting project, but with a lot of challenges. 
We have never done such simulations in our group, so we do not have any relevant experience. I would assume that what you propose makes sense, to have ground-state samples from the correct grand canonical ensemble (constant pH) and use them as initial conditions. If the excited-state simulations are not very long, then one could assume that within this short time the protonation state does not change dramatically, so that one could run the SHARC simulations without explicit constant pH algorithm. I would expect that this works better the bigger your solvent droplet is (because the exchange of protons with the environment happens there and a larger shell will make it take longer to affect the molecule). Also keep in mind that even with a big droplet, protons could jump anywhere within your droplet at any time (time constant is about 1ps 10.1021/acscentsci.9b00603). These proton jumps cannot be described currently with SHARC QM/MM, because normal force fields have fixed water molecules.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, sounds like an interesting project, but with a lot of challenges. We have never done such simulations in our group, so we do not have any relevant experience. I would assume that what you propose makes sense, to have ground-state samples from the correct grand canonical ensemble (constant pH) and use them as initial conditions. If the excited-state simulations are not very long, then one could assume that within this short time the protonation state does not change dramatically, so that one could run the SHARC simulations without explicit constant pH algorithm. I would expect that this works better the bigger your solvent droplet is (because the exchange of protons with the environment happens there and a larger shell will make it take longer to affect the molecule). Also keep in mind that even with a big droplet, protons could jump anywhere within your droplet at any time (time constant is about 1ps 10.1021/acscentsci.9b00603). These proton jumps cannot be described currently with SHARC QM/MM, because normal force fields have fixed water molecules.
> 
> Best, Sebastian

Dear Sir,
Thank you for your prompt response to my previous queries. From our experimental data, we have thought that intermolecular proton transfer (molecule to solvent) occurs at different pH levels. I have a question, if we include water molecules with our molecule in the QM region of a QM/MM simulation, could we observe the proton transfer process directly?

Additionally, I recently came across a thesis from your group titled "Excited State Dynamics of 5,6-Dihydroxyindole, a Eumelanin Building Block in Water and Methanol." I noticed an image describing proton transfer between DHI and the solvent, which was adapted from a paper from your group titled "Sequential Proton-Coupled Electron Transfer Mediates Excited-State Deactivation of a Eumelanin Building Block." I believe this approach may offer a solution to my research problem.

If possible, could you kindly share a copy of the thesis to read more about this approach?

Thank you once again for your guidance and support.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear user,
indeed, if you have proton transfer between water and solute, then it is important to have water molecules in the QM region. Be aware that we did not do something like that in SHARC before. Depending on your initial conditions, it might be that different waters are near the molecule in each initcond, so you might need to reorder the waters appropriately, so that, e.g., the first 5 waters are the ones near the molecule. A simpler, but more approximate way would be to run the SHARC simulations with only a few waters, and have no MM region.

The thesis you mentioned is publicly available from the univie archive: https://utheses.univie.ac.at/detail/42935#

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear user, indeed, if you have proton transfer between water and solute, then it is important to have water molecules in the QM region. Be aware that we did not do something like that in SHARC before. Depending on your initial conditions, it might be that different waters are near the molecule in each initcond, so you might need to reorder the waters appropriately, so that, e.g., the first 5 waters are the ones near the molecule. A simpler, but more approximate way would be to run the SHARC simulations with only a few waters, and have no MM region.
> 
> The thesis you mentioned is publicly available from the univie archive: https://utheses.univie.ac.at/detail/42935#
> 
> Best, Sebastian

Dear Sir,
Thank you for your reply.

Best regards,
Lukhmanul Hakeem K

**Comment by lukhman9020** [comment]
> Dear user, indeed, if you have proton transfer between water and solute, then it is important to have water molecules in the QM region. Be aware that we did not do something like that in SHARC before. Depending on your initial conditions, it might be that different waters are near the molecule in each initcond, so you might need to reorder the waters appropriately, so that, e.g., the first 5 waters are the ones near the molecule. A simpler, but more approximate way would be to run the SHARC simulations with only a few waters, and have no MM region.
> 
> The thesis you mentioned is publicly available from the univie archive: https://utheses.univie.ac.at/detail/42935#
> 
> Best, Sebastian

Dear Sir,

I am currently sampling 90 initial conditions using the AMBER interface and focusing on QM simulations (SHARC-MOLCAS) to study proton transfer between water and my molecule. I would like to clarify the following:

Is the MOLCAS quantum chemistry interface sufficient for these calculations, or is there any additional requirement to use TINKER or provide a force field for the system?

Looking forward to hearing from you.

Best regards,
Lukhmanul Hakeem K

**Comment by lukhman9020** [comment]
Dear Sir 
I am currently working on simulating the excited-state dynamics of a molecule under three different pH conditions: 3, 7, and 9. My workflow involves performing classical molecular dynamics simulations at these pH values, followed by QM/MM simulations using the Amber/Gaussian interface. I also plan to prepare initial conditions from these simulations for surface hopping dynamics using the SHARC 3.0 package.

To decrease the simulation time, I aim to select only water molecules within 2.4 Å of my solute for further steps(SHARC dynamics and do only QM simulation). However, I am facing challenges with performing Constant pH Molecular Dynamics simulations for this system, as most tutorials available are tailored for proteins. The primary difficulty lies in preparing the CPIN input file for my small molecule.

As an alternative, I am considering two separate simulations: one starting with the protonated form of the molecule (to represent pH = 3) and another with the deprotonated form (to represent pH values above 7). This approach is based on the expectation that the molecule is protonated at pH 3 and deprotonated at higher pH levels. However, I am unsure if this approach will give my experimental results and could you please verify whether this method is valid or not?

If possible, could you kindly provide guidance or a tutorial on preparing the CPIN input file for a small molecule in Constant pH Molecular Dynamics? I know that Constant pH Molecular Dynamics is not directly related to the SHARC part. However, I reached out via email to request a tutorial describing this method but have not received a response. so could you please help me?

Looking forward to hearing from you.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear Lukhmanul,
nobody in our research group has any experience with Amber's constant-pH methods, so unfortunately I cannot provide any guidance here.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, nobody in our research group has any experience with Amber's constant-pH methods, so unfortunately I cannot provide any guidance here.
> 
> Best, Sebastian

Dear Sir,
Thanks for your reply.

Best regards,
Lukhmanul Hakeem K

**Comment by lukhman9020** [comment]
> Dear user, indeed, if you have proton transfer between water and solute, then it is important to have water molecules in the QM region. Be aware that we did not do something like that in SHARC before. Depending on your initial conditions, it might be that different waters are near the molecule in each initcond, so you might need to reorder the waters appropriately, so that, e.g., the first 5 waters are the ones near the molecule. A simpler, but more approximate way would be to run the SHARC simulations with only a few waters, and have no MM region.
> 
> The thesis you mentioned is publicly available from the univie archive: https://utheses.univie.ac.at/detail/42935#
> 
> Best, Sebastian

Dear Sir,

I have completed the classical MD simulation to sample the initial condition for doing SHARC dynamics. As per your instruction, I am trying to run SHARC dynamics with only my solute and 5 water molecules. To do this, I selected the 5 water molecules near the solute molecule using the cpptraj tool and created a new rst7 file.

However, when I try to run the command below, just for testing with two geometries:
"
$SHARC/amber_to_initconds.py -t 0.002 -o initconds molecule.prmtop 04_Prod410000.rst7 04_Prod420000.rst7  
"
I encounter the following error:
"
Initial condition generation started...
prmtop file                  = "molecule.prmtop"
rst files                    = "['04_Prod410000.rst7', '04_Prod420000.rst7']"
OUTPUT file                  = "initconds"
Number of geometries         = 2
Traceback (most recent call last):
  File "/home/mhgroup1/kumar/sharc/bin/amber_to_initconds.py", line 1038, in <module>
    main()
  File "/home/mhgroup1/kumar/sharc/bin/amber_to_initconds.py", line 1018, in main
    molecule, ic_list = get_coords(INFOS)
  File "/home/mhgroup1/kumar/sharc/bin/amber_to_initconds.py", line 862, in get_coords
    line = data[iline]
IndexError: list index out of range
"

I noticed that I am using an older prmtop file with a higher number of water molecules. Could this be causing the issue? Do I need to generate a new topology file with only 5 water molecules? I am unsure of the correct procedure to resolve this.

I kindly request your guidance in resolving this issue.

Best regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
Yes, you need to generate a new prmtop file with the exact number of water molecules. The `closestwaters` command in cpptraj already does this, you just need to add the `parmout` option to the `closestwaters` command.

**Comment by lukhman9020** [comment]
> Yes, you need to generate a new prmtop file with the exact number of water molecules. The `closestwaters` command in cpptraj already does this, you just need to add the `parmout` option to the `closestwaters` command.

Dear Sir, 
Thank you for your reply.

Best regards,
Lukhmanul Hakeem K.

**Comment by lukhman9020** [comment]
Dear Sir,
I am writing to seek your assistance regarding an issue I encountered while running TD-DFT single point energy calculations using the CAM-B3LYP/aug-cc-pVDZ level of theory. I am performing calculations on a system consisting of my molecule with five water molecules, and I am running only QM calculations (not QM/MM).

The initial conditions were generated from classical MD simulations, and I successfully completed the calculation for ICOND_00000. However, when attempting to run ICOND_00001, the calculation stopped after approximately six hours. The qm.log file contains the following output:
"
>>>>>>>>>>> Starting the WFOVERLAP job execution  
START:  /home/mhgrou...cra/ICOND_00019/AOoverlap  2025-01-21 17:58:57.590421 "/opt/apps/ga...an/g16/g16 < GAUSSIAN.com"  
FINISH: /home/mhgrou...cra/ICOND_00019/AOoverlap  2025-01-21 17:59:03.237186 Runtime: 0:00:05.646765 Error Code: 0  
START:  /home/mhgrou...cra/ICOND_00019/WFOVL_1_1  2025-01-21 17:59:05.010377 "/home/mhgrou...ap.x -m 4000 -f wfovl.inp"  
FINISH: /home/mhgrou...cra/ICOND_00019/WFOVL_1_1  2025-01-21 17:59:06.815504 Runtime: 0:00:01.805127 Error Code: 1  
START:  /home/mhgrou...cra/ICOND_00019/WFOVL_3_3  2025-01-21 17:59:06.926022 "/home/mhgrou...ap.x -m 4000 -f wfovl.inp"  
FINISH: /home/mhgrou...cra/ICOND_00019/WFOVL_3_3  2025-01-21 17:59:07.290867 Runtime: 0:00:00.364845 Error Code: 1  

Error Codes:  
    WFOVL_1_1 1 WFOVL_3_3 1  

Some subprocesses did not finish successfully!
"
The corresponding qm.err file includes the following message:
"
/home/mhgroup1/Vivek/s/psi4conda/etc/profile.d/conda.cshnconda: No such file or directory
"
However, I believe the error is unrelated to the Conda environment, as I am using the Bourne shell, not C-shell.

Further investigation into the WFOVL_3_3/wfovl.err file indicates the following error message:
"
read_col_moheader: MOcoef file states different number of atomic orbitals than AOoverlap file. naotmp = 552, nao = 553
"
I suspect the issue arises from a mismatch between the number of atomic orbitals in the molecular orbital coefficient file and the AO overlap file. I am considering whether removing reference overlap could help resolve the issue?

I have uploaded the input and output files for your reference at the following link:
https://drive.google.com/drive/folders/1F3BLtrgXf0vCW9eRpAnfU4uZ_m-Xxgi4?usp=drive_link

I would greatly appreciate your guidance on resolving this issue.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear Lukhmanul,
yes, you have mostly correctly identified the problem. It looks like the wfoverlap calculations do not succeed because there is some mismatch between the number of orbitals that are in the AO overlap file and in the MO coefficient file. However, from the files that you had attached, I cannot resolve this issue. 
Some questions or things you could check:
- check the Gaussian output what number of basis functions you expect (552 or 553?)
- does the calculation use spherical or cartesian d/f/... functions?
- do you use any ECPs?
- Check QM.log what number of frozen core the interface wants to use
- What chemical sum formula does your system have and what basis set do you use (aug-cc-pvdz throughout?)

Feel free to send me the Gaussian output, but note that in the next weeks I will not be very available for personal reasons.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, yes, you have mostly correctly identified the problem. It looks like the wfoverlap calculations do not succeed because there is some mismatch between the number of orbitals that are in the AO overlap file and in the MO coefficient file. However, from the files that you had attached, I cannot resolve this issue. Some questions or things you could check:
> 
> * check the Gaussian output what number of basis functions you expect (552 or 553?)
> * does the calculation use spherical or cartesian d/f/... functions?
> * do you use any ECPs?
> * Check QM.log what number of frozen core the interface wants to use
> * What chemical sum formula does your system have and what basis set do you use (aug-cc-pvdz throughout?)
> 
> Feel free to send me the Gaussian output, but note that in the next weeks I will not be very available for personal reasons.
> 
> Best, Sebastian

Dear Sir,
I am writing to follow up regarding the error-related issue I previously mentioned. I have tried to resolve it on my own but was unable to understand how to fix the problem. I look forward to your response.

Best regards,
Lukhmanul Hakeem K.

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, yes, you have mostly correctly identified the problem. It looks like the wfoverlap calculations do not succeed because there is some mismatch between the number of orbitals that are in the AO overlap file and in the MO coefficient file. However, from the files that you had attached, I cannot resolve this issue. Some questions or things you could check:
> 
> * check the Gaussian output what number of basis functions you expect (552 or 553?)
> * does the calculation use spherical or cartesian d/f/... functions?
> * do you use any ECPs?
> * Check QM.log what number of frozen core the interface wants to use
> * What chemical sum formula does your system have and what basis set do you use (aug-cc-pvdz throughout?)
> 
> Feel free to send me the Gaussian output, but note that in the next weeks I will not be very available for personal reasons.
> 
> Best, Sebastian

Dear Sir,

I hope you are doing well. I would like to clarify whether the mos.1 and mos.3 files are generated from the respective Gaussian calculations running in the master_1 and master_3 directories and whether the AO overlap file should be prepared from the results of the Gaussian calculation running in the AOoverlap directory.

Upon checking the log files in the master_1 and master_3 directories, I observed that NBasis = 553 and NBsUse = 552. Additionally, when I checked the log file in the AOoverlap directory, I found that NBasis = 1106 and NBsUse = 1070. This discrepancy in NBasis and NBsUse values raises a concern about a possible mismatch between the number of orbitals in the AO overlap file and the MO coefficient file.

Could this issue be resolved using Gaussian keywords like "ChkBasis" and "pop=NBO"? I would greatly appreciate your guidance on this matter. Thank you for your time and consideration. I look forward to your response.

Best Regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
Dear Lukhmanul,
I am still on a family-related leave of absence. 

What you write sounds reasonable. There are some cases where QC software reduces the size of the basis, if the basis functions are linearly dependent (too many similar basis functions close to each other). In Gaussian, you can turn off this check apparently with IOP(3/32=2). You can try to add this keyword to the template file via `iop 3/32=2` (the interface will add the parenthesis).

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, I am still on a family-related leave of absence.
> 
> What you write sounds reasonable. There are some cases where QC software reduces the size of the basis, if the basis functions are linearly dependent (too many similar basis functions close to each other). In Gaussian, you can turn off this check apparently with IOP(3/32=2). You can try to add this keyword to the template file via `iop 3/32=2` (the interface will add the parenthesis).
> 
> Best, Sebastian

Dear Sir,
Thank you for your response. I thought you were back at work, which is why I put my question there. I sincerely apologize for this.

Best Regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
Dear Lukhmanul,
did you try the IOP(3/32=2) option? I have now briefly looked at the Gaussian outputs you sent. While I am not completely sure, I guess that Gaussian deletes basis functions due to linear dependency. This should get more severe with bigger basis sets. Can you try without augmentation functions or with a generally small basis set? If the error still persists in these cases, then we need to investigate further.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, did you try the IOP(3/32=2) option? I have now briefly looked at the Gaussian outputs you sent. While I am not completely sure, I guess that Gaussian deletes basis functions due to linear dependency. This should get more severe with bigger basis sets. Can you try without augmentation functions or with a generally small basis set? If the error still persists in these cases, then we need to investigate further.
> 
> Best, Sebastian

Dear Sir,

I apologize for not informing you earlier. I had already tried with IOP(3/32=2) and with the 6-311++G(d,p) basis set, and the calculation was completed without any error. Thank you for your support.

Best regards,
Lukhmanul Hakeem K

**Comment by lukhman9020** [comment]
Dear Sir,
I am currently performing dynamics simulations following the SHARC tutorial ([link](https://sharc-md.org/wp-content/uploads/2023/04/SHARC_Tutorial.pdf)). My simulations use a time step of 0.5 fs with 25 substeps for propagation over 1000 fs. To assess the computational efficiency, I ran a single trajectory and observed that running from 0 to 0.5 fs takes approximately 25 minutes. Based on this, I estimate that completing the full 1000 fs simulation would take more than a month.

Since I am particularly interested in observing proton transfer, I am looking for ways to reduce the computational cost while maintaining accuracy. Would decreasing the number of substeps for propagation from 25 to 10 or 15 significantly reduce the computational time? If so, would this still be sufficient to capture proton transfer dynamics effectively? Are there any other recommended optimizations to improve efficiency without losing essential dynamics?
I kindly request your guidance in resolving this issue.

Best regards,
Lukhmanul Hakeem K

**Comment by maisebastian** [comment]
Dear Lukhmanul,
the substeps have no influence on the cost of the simulation. Only the main time step (0.5fs) decides at which times electronic structure calculations are done, and those account for ~100% of the simulation time.

Also note that from 0 to 0.5fs is two time steps, the one at 0fs and the one at 0.5fs. The one at 0fs is typically a bit more expensive than later steps. So I guess your estimation is a bit on the high side, I would rather expect around 2,5 weeks for 2000 steps.

To increase computation speed, you can consider:
- reduce the number of states if possible
- use gradient selection option (might be active already)
- parallelize your trajectories if you have the resources. Golden rule: Never parallelize unless you have more CPU cores than trajectories
- use a more appropriate basis. With the "basis_external" keyword of GAUSSIAN.template, you can define different basis sets for different atoms. I recommend that you use a double zeta basis set throughout, and only augment the atoms that are important. Make some tests before that this gives good results. 
- Adjust the integration grid (but check the total energy conservation)
- Check whether denfit accelerates your dynamics
- From your Google drive files, I saw that you include triplet states. But Gaussian does not have SOCs, so the triplets cannot be populated. Consider removing the triplets. If you need them, you can perform single point calculations a posteriori.

Best,
Sebastian

**Comment by lukhman9020** [comment]
> Dear Lukhmanul, the substeps have no influence on the cost of the simulation. Only the main time step (0.5fs) decides at which times electronic structure calculations are done, and those account for ~100% of the simulation time.
> 
> Also note that from 0 to 0.5fs is two time steps, the one at 0fs and the one at 0.5fs. The one at 0fs is typically a bit more expensive than later steps. So I guess your estimation is a bit on the high side, I would rather expect around 2,5 weeks for 2000 steps.
> 
> To increase computation speed, you can consider:
> 
> * reduce the number of states if possible
> * use gradient selection option (might be active already)
> * parallelize your trajectories if you have the resources. Golden rule: Never parallelize unless you have more CPU cores than trajectories
> * use a more appropriate basis. With the "basis_external" keyword of GAUSSIAN.template, you can define different basis sets for different atoms. I recommend that you use a double zeta basis set throughout, and only augment the atoms that are important. Make some tests before that this gives good results.
> * Adjust the integration grid (but check the total energy conservation)
> * Check whether denfit accelerates your dynamics
> * From your Google drive files, I saw that you include triplet states. But Gaussian does not have SOCs, so the triplets cannot be populated. Consider removing the triplets. If you need them, you can perform single point calculations a posteriori.
> 
> Best, Sebastian

Dear Sir,

Thank you for your response. As per your suggestion, I will reduce the number of states and consider only three singlet states, as our experiments are conducted at the end of the absorption spectrum. 
Regarding the computational setup, I have enabled gradient calculations (Select gradients? [False] yes). I tested a single trajectory using 28 CPU cores (1 node), which took 25 minutes to compute the first time step (0.0 fs to 0.5 fs). Running the same trajectory on 1 CPU core took 9 hours for the same step.

I have access to 112 CPU cores (4 nodes) and need to run 112 trajectories. Given these constraints, I plan to use 1 CPU core per trajectory and expect that reducing the number of states will help decrease the computational cost.

I also have a question regarding the schedule_scaling parameter. If I use 1 CPU core per trajectory, would schedule_scaling = 1.000 or 0.9000 be more optimal?

To further reduce the computational cost, I have already replaced aug-cc-pVDZ with 6-311++G(d,p), I hope this can capture proton transfer. Additionally, I plan to use the basis_external keyword as per your suggestion like below:

6-31G* for all carbon atoms
6-311++G(d,p) for oxygen and hydrogen atoms

Regarding the integration grid, I am currently using "grid finegrid".

Lastly, as per your suggestion, I will use the densfit keyword.

Please let me know if these adjustments seem appropriate or if further modifications are required.


Best regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
Well, if one time step takes 9h, then you need to speed up the trajectories significantly to make the project work. To finish 2000 steps in 1 week requires that one time step takes 5 min at most, and in your case on 1 CPU core. 

Some more hints to speed up the computations:
- use a fast local scratch file system for "scratchdir"
- switch to ORCA, which is faster
- with SHARC_ORCA.py you can assign different basis sets to atoms of the same element so you can use the augmented basis only for those H and O atoms that matter
- on 1 CPU core, parallel scaling does not matter, you can ignore this setting
- check how long the wfoverlap calculation takes, adjust the wfthreshold slightly to make it cheaper (such that it takes below 1 min)

**Comment by lukhman9020** [comment]
> Well, if one time step takes 9h, then you need to speed up the trajectories significantly to make the project work. To finish 2000 steps in 1 week requires that one time step takes 5 min at most, and in your case on 1 CPU core.
> 
> Some more hints to speed up the computations:
> 
> * use a fast local scratch file system for "scratchdir"
> * switch to ORCA, which is faster
> * with SHARC_ORCA.py you can assign different basis sets to atoms of the same element so you can use the augmented basis only for those H and O atoms that matter
> * on 1 CPU core, parallel scaling does not matter, you can ignore this setting
> * check how long the wfoverlap calculation takes, adjust the wfthreshold slightly to make it cheaper (such that it takes below 1 min)

Dear Sir,

Thank you for your response. I will make the necessary adjustments to my calculations as per your suggestions.

I have a question regarding the generation of the absorption spectrum. Initially, I used FWHM = 0.1 eV, but the resulting spectrum did not match the experimental data, as it showed zero absorbance at 250 nm. However, when I increased FWHM to 0.5 eV, the spectrum became more similar to the experimental results and showed absorbance at 250 nm.

I am unsure whether increasing the FWHM value introduces any issues. Could you please clarify if this adjustment is acceptable?

Additionally, I would like to know which line shape function is more appropriate for generating the spectrum—Gaussian or Lorentzian? 
Looking forward to your insights.

Best regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
For molecules, for which the broadening of the spectrum mostly arises from nuclear motion out of the FC region, a Gaussian is more appropriate. A Lorentzian is more appropriate if the dominant excited-state decay is exponential (like in atomic spectrosocpy or vibrational spectroscopy).

In my opinion, the used FWHM is mostly dependent on the number of snapshots that you use. We generally choose the FWHM as narrow as possible, but as wide as necessary to remove any artificial "fine structure" from the spectrum that arises from a small number of samples. You should not use the FWHM to make the spectrum look like an experimental reference. If your spectrum does not match the experimental absorption lines, then possibly your electronic structure method is not good enough (correlation missing, states missing, wrong basis, missing solvent effects, etc). Still, in some cases one can use the method, and should openly discuss the shifts between experiment and simulation.

**Comment by lukhman9020** [comment]
> For molecules, for which the broadening of the spectrum mostly arises from nuclear motion out of the FC region, a Gaussian is more appropriate. A Lorentzian is more appropriate if the dominant excited-state decay is exponential (like in atomic spectrosocpy or vibrational spectroscopy).
> 
> In my opinion, the used FWHM is mostly dependent on the number of snapshots that you use. We generally choose the FWHM as narrow as possible, but as wide as necessary to remove any artificial "fine structure" from the spectrum that arises from a small number of samples. You should not use the FWHM to make the spectrum look like an experimental reference. If your spectrum does not match the experimental absorption lines, then possibly your electronic structure method is not good enough (correlation missing, states missing, wrong basis, missing solvent effects, etc). Still, in some cases one can use the method, and should openly discuss the shifts between experiment and simulation.

Dear Sir,
Thank you for your response, I apologize for my delayed response to your message. I was attending a conference, which caused the delay in my reply. I am using a total of 480 initial conditions (each initial condition represents a cluster model of my molecule with approximately seven water molecules). My concern arises when I inspect a single initial condition file while the calculation is running. Specifically, when I generate a UV-Vis spectrum in Gaussian using the log file from the master_1 directory (for example, the ICOND_00001 file), I observe a spectrum that closely matches the experimental results. However, when I generate the ensemble spectrum using the SHARC script with a full width at half maximum (FWHM) of 0.1 eV, I notice a significant discrepancy. If possible, can I share the experimental and simulated spectra via email or drive for your reference? 
Looking forward to your response.

Best regards,
Lukhmanul Hakeem K.

**Comment by maisebastian** [comment]
Yes, you can share your results via email.

However, note that what you write does not really make sense: If one single ICOND calculation matches the experimental absorption maximum, then you should consider this pure coincidence. The absorption spectrum arises from a combination of all possible geometries, so any single geometry is not statistically significant. To see this better, you can try to generate the line spectrum using spectrum.py. Maybe you find that the ICOND_00001 is an outlier... 

Also note that ICOND_00000 has no special significance if you generate the initconds file from MD simulations. In this case, ICOND_00000 is simply identical to ICOND_00001. This is different with wigner.py, where ICOND_00000 is the equilibrium geometry.

**Comment by lukhman9020** [comment]
> Yes, you can share your results via email.
> 
> However, note that what you write does not really make sense: If one single ICOND calculation matches the experimental absorption maximum, then you should consider this pure coincidence. The absorption spectrum arises from a combination of all possible geometries, so any single geometry is not statistically significant. To see this better, you can try to generate the line spectrum using spectrum.py. Maybe you find that the ICOND_00001 is an outlier...
> 
> Also note that ICOND_00000 has no special significance if you generate the initconds file from MD simulations. In this case, ICOND_00000 is simply identical to ICOND_00001. This is different with wigner.py, where ICOND_00000 is the equilibrium geometry.

Dear Sir,

Thank you for your response. I will share the files via email.

Best regards,
Lukhmanul Hakeem K.
