### ISSUE TITLE
Is it possible to support ORCA 5.0.3? 

### ISSUE THREAD

**Issue by abbottjlu** [sharc-md/sharc#32]
By disabling the keyword _grid_ in ORCA.template, 
the **setup_LVCparam** runs smoothly with ORCA 5.0.3. 

But there is no QM.out file under DSPL_RESULTS/DSPL_XXX folders. 

QM.err reports, 

> Traceback (most recent call last):
  File "/opt/share/apps/sharc-2.1.1/source/../bin/SHARC_ORCA.py", line 5011, in <module>
    main()
  File "/opt/share/apps/sharc-2.1.1/source/../bin/SHARC_ORCA.py", line 4985, in main
    QMin,QMout=getQMout(QMin)
  File "/opt/share/apps/sharc-2.1.1/source/../bin/SHARC_ORCA.py", line 4233, in getQMout
    energies=getenergy(logfile,job,QMin)
  File "/opt/share/apps/sharc-2.1.1/source/../bin/SHARC_ORCA.py", line 4573, in getenergy
    e=gsenergy+float(s[-2])*rcm_to_Eh
ValueError: could not convert string to float: =

It seems that SHARC fails to get the energy from the ORCA 5 output file.

**Comment by maisebastian** [comment]
Dear user,
this seems to be because ORCA 5 is printing S**2 expectation values in the same lines as the energies. If you change line 4573 to include s[-5], then this error should disappear. 

Best,
Sebastian
