### ISSUE TITLE
Problem during sharc-molcas interface while following tutorial

### ISSUE THREAD

**Issue by Kalpa08** [sharc-md/sharc#45]
**Dear developers**

I am running the calculations given in the tutorial. I did the first step (freq and optimization). Then I generated the initial conditions using setup_init.py, prior to that I created the MOLCAS.template file to interface SHARC-MOLCAS.
While running the setup_init.py script I faced some odd problems as follow:

**In ICOND_00000 directory, the following error came**

[kalpa.bhu@login1 ICOND_00000]$ cat QM.log 
2023-04-20 11:30:15.213290 cn077 /home/kalpa.bhu/CALC/sharc/tutorial/wigner/init/ICOND_00000

  ================================================================================
||                                                                                ||
||                           SHARC - MOLCAS - Interface                           ||
||                                                                                ||
||                   Authors: Sebastian Mai and Martin Richter                    ||
||                                                                                ||
||                                  Version: 2.1                                  ||
||                                 Date: 01.09.19                                 ||
||                                                                                ||
  ================================================================================

MOLCAS version 22.1 not supported! 

**In the rest of the directories I found different error as follow:**

[kalpa.bhu@login1 init]$ cd ICOND_00001/
[kalpa.bhu@login1 ICOND_00001]$ cat QM.log 
2023-04-20 11:30:15.303933 cn077 /home/kalpa.bhu/CALC/sharc/tutorial/wigner/init/ICOND_00001

  ================================================================================
||                                                                                ||
||                           SHARC - MOLCAS - Interface                           ||
||                                                                                ||
||                   Authors: Sebastian Mai and Martin Richter                    ||
||                                                                                ||
||                                  Version: 2.1                                  ||
||                                 Date: 01.09.19                                 ||
||                                                                                ||
  ================================================================================

File "MOLCAS.1.JobIph" missing in SAVEDIR!
File "MOLCAS.3.JobIph" missing in SAVEDIR!
2 files missing in SAVEDIR=/home/kalpa.bhu/CALC/sharc/tutorial/wigner/init/ICOND_00001/SAVE
[kalpa.bhu@login1 ICOND_00001]$ 

I am attaching both the directories [Opt_freq](https://drive.google.com/drive/folders/1IaX5esa2kFYQ4rpPuuaEmFG_VqisFMWJ?usp=share_link) and  [initial condition ](https://drive.google.com/drive/folders/1wqnjQCefbKaSL7Ww9yiwJtphwwYpVv_k?usp=share_link) directories.

**Kindly look into this matter, help us to resolve the issue.**

**Comment by maisebastian** [comment]
The problem with the unsupported version should be gone if you use the new SHARC 3.0 release version. The other errors (File ... missing) should also go away once ICOND_00000 runs successfully.

**Comment by Kalpa08** [comment]
Okay then, I will have to install the sharc 3.0

**Comment by Kalpa08** [comment]
Can you please tell me where can I find the 3.0 version? I downloaded from [here](https://sharc-md.org/wp-content/uploads/2023/04/sharc-3.0.0.zip) and after compiling( without pysharc) I see the following (mentioning version 2.1):

[kalpa@compute ~]$ /opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/tests.py 

  ================================================================================
||                                                                                ||
||                          SHARC Test suite run script                           ||
||                                                                                ||
||                             Author: Sebastian Mai                              ||
||                                                                                ||
||                                  Version:2.1                                   ||
||                                    14.08.19                                    ||
||                                                                                ||
  ================================================================================


This script collects a number of environment variables and subsequently runs
the calculations in the SHARC test suite. After the runs, the output is checked
against the reference outputs.

**Comment by maisebastian** [comment]
Sorry for the confusion. The scripts in this zip are from version 3.0, but the version information inside the scripts was not updated yet. It should still work if you try to run your previous computation with the new SHARC_MOLCAS.py

**Comment by Kalpa08** [comment]
Okay, I will ignore this comment.
I compiled without pysharc and after running the **$SHARC/wigner.py -n 20 MOLCAS.freq.molden**  command I found the following error. 

[kalpa@compute wigner]$ $SHARC/wigner.py -n 20 MOLCAS.freq.molden 
Initial condition generation started...
INPUT  file                  = "MOLCAS.freq.molden"
OUTPUT file                  = "initconds"
Number of geometries         = 20
Random number generator seed = 16661
Temperature                  = 0.000000

***************************************************
WARNING: Less than 3*N_atom normal modes extracted!
***************************************************


Starting normal mode format determination...
Final format specifier: 2 [cartesian (Molpro, Molcas)]
Multiple possible flags have been identified: 
  gaussian-type (Gaussian, Turbomole, Q-Chem, AMS, Orca) 
  cartesian (Molpro, Molcas)
The most likely assumption is cartesian (Molpro, Molcas) coordinates.
These have been used in the creation of inital conditions.

You can override this behavior by setting the -f [int] flag in the command line:
  1	gaussian-type (Gaussian, Turbomole, Q-Chem, AMS, Orca)
  2	cartesian (Molpro, Molcas)
  3	columbus-type (Columbus)
  4	mass-weighted


Geometry:
 C   6.0  -0.00000017   0.00000000  -1.27117017  12.00000000 
 H   1.0  -0.00000150  -1.77797173  -2.28154646   1.00782500 
 H   1.0   0.00000166   1.77797172  -2.28154648   1.00782500 
 N   7.0  -0.00000011   0.00000001   1.13411757  14.00307400 
 H   1.0   0.00000179  -1.62558496   2.13640331   1.00782500 
 H   1.0  -0.00000166   1.62558496   2.13640334   1.00782500 
Assumed Isotopes: N-14 H-1 C-12 
Isotopes with * are pure isotopes.

Frequencies (cm^-1) used in the calculation:
   1     973.6280
   2    1022.2529
   3    1213.7376
   4    1313.0204
   5    1417.9914
   6    1537.8078
   7    1679.3847
   8    1882.7693
   9    3330.1393
  10    3463.9920
  11    3679.8740
  12    3763.0580

Sampling initial conditions
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/wigner.py", line 1524, in <module>
    main()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/wigner.py", line 1504, in main
    ic_list = create_initial_conditions_list(amount, molecule, modes)
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/wigner.py", line 1317, in create_initial_conditions_list
    sys.stdout.write('\rProgress: [' + '=' * done + ' ' * (width - done) + '] %3i%%' % (done * 100 / width))
TypeError: can't multiply sequence by non-int of type 'float'
[kalpa@compute wigner]$ ls
MOLCAS.freq.molden  MOLCAS.input  MOLCAS.RasOrb
[kalpa@compute wigner]$ 


Can you please tell me how can I remove this error?

**Comment by maisebastian** [comment]
In line 1316 of wigner.py, you have to add a second "/" so that it reads:
        done = idone * width // (amount)
We will put the bugfix into the release code of 3.0.1

**Comment by Kalpa08** [comment]
I have corrected and recompiled (without pysharc).  That problem with  $SHARC/wigner.py -n 20 MOLCAS.freq.molden is resolved, but when I have run **all_run_init.sh** script after execution of $SHARC/setup_init.py, I have encountered the following error in the **ICOND_00000**  directory:

[kalpa@compute ICOND_00000]$ tail QM.log 
delay: 0.0
method: 0
gradmode: 0
version: 23.02


>>>>>>>>>>>>> Starting the job execution
START:	/home/scratch/SHARC/ICOND_00000/master	2023-04-20 15:18:17.643367	"/opt/SOFTWARES/openmolcas/parallel_Mlcs/bin/pymolcas MOLCAS.input"
FINISH:	/home/scratch/SHARC/ICOND_00000/master	2023-04-20 15:18:18.085747	Runtime: 0:00:00.442380	Error Code: 1
File /home/scratch/SHARC/ICOND_00000/master/MOLCAS.1.JobIph not found, cannot move to savedir!
[kalpa@compute ICOND_00000]$ 



**In the rest of the directories I saw the following error although we used MOLCAS.RasOrb during** **Setup of initial calculations**:



2023-04-20 15:18:18.669135 compute.server /home/kalpa/CALC/sharc/wigner/init/ICOND_00002

  ================================================================================
||                                                                                ||
||                           SHARC - MOLCAS - Interface                           ||
||                                                                                ||
||                     Authors: Sebastian Mai, Martin Richter,                    ||
||               Severin Polonius, Philipp Marquetand and Yinan Shu               ||
||                                                                                ||
||                                  Version: 3.0                                  ||
||                                 Date: 03.02.23                                 ||
||                                                                                ||
  ================================================================================


File "MOLCAS.1.JobIph" missing in SAVEDIR!
File "MOLCAS.3.JobIph" missing in SAVEDIR!
2 files missing in SAVEDIR=/home/kalpa/CALC/sharc/wigner/init/ICOND_00002/SAVE
~                                                                             


Can you please look into my [files](https://drive.google.com/drive/folders/14KQGW4aDk1E3BKF0aFrnO36Usl1x4XTe?usp=share_link)  and let me know is there any problem from my side?

**Comment by maisebastian** [comment]
The error in ICOND_00000 seems to be because your Molcas did not run correctly. As you can, see, the interface says "Error Code: 1". Go to the scratch directory to check why Molcas did not run. The error message about the JobIph files is because after the failed Molcas call, it could not copy back the JobIph files.

**Comment by Kalpa08** [comment]
There was no such information written in the files present at the scratch directory. Although I gave a try by loading the intel libraries and compilers, it has worked now. All the files in the ICOND000* are ending with

|                                            |                                 |                                 |-7.593e-02 -2.727e-02  9.517e-01 |
---------------------------------------------------------------------------------------------------------------------------------------------------

==> Runtime:
0 Days  0 Hours 0 Minutes       8 Seconds


===> Writing output to file QM.out in SHARC Format

===> Removing directory /home/scratch/SHARC/ICOND_00010

===> Removing directory /home/kalpa/CALC/sharc/wigner/init/ICOND_00010/SAVE

#================ END ================#


I hope the calculation is successful. Moreover I would like to ask you about one more thing regarding the compilation as I have compiled it without pysharc as "with pysharc" during compilation I had some library issues. Will it create problem in my work even if I continue with this simple compilation or should I recompile using pysharc ?

**Comment by maisebastian** [comment]
The output looks like the calculation was successful now ("Writing output to file QM.out" is the most important line here).

pysharc is only needed for certain features. It is intended to run super efficient trajectories with LVC model potentials, and it is somewhat useful for QM/MM, because it makes the output files smaller. If you use ab initio interfaces and no QM/MM, you will not need pysharc.

**Comment by Kalpa08** [comment]
**We will need the use of pysharc for such uses. I am trying to compile it, but facing some errors while compiling with pysharc as follow:**

(pysharc_3.0) [root@compute pysharc]# make
cd ../source; make libsharc
make[1]: Entering directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
Updating "build_info.inc"
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c definitions.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c matrix.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c string.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c input_list.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c misc.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c output.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_afssh.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_dom.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c nuclear.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c electronic.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c qm_out.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c restart.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c qm.f90
qm.f90:3167:27:

 3167 |        do 100 jatom=1,iatom
      |                           1
Warning: Fortran 2018 deleted feature: Shared DO termination label 100 at (1)
qm.f90:3172:26:

 3172 |            do 70 jc=1,jend
      |                          1
Warning: Fortran 2018 deleted feature: Shared DO termination label 70 at (1)
qm.f90:3175:27:

 3175 |                do 50 ib=1,3
      |                           1
Warning: Fortran 2018 deleted feature: Shared DO termination label 50 at (1)
qm.f90:3178:31:

 3178 |                    do 30 jb=1,3
      |                               1
Warning: Fortran 2018 deleted feature: Shared DO termination label 30 at (1)
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c bsh.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c electronic_laser.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c input.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c zpe.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c army_ants.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c tsh_tu.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c pointer_basis.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c driver.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c definitions_NetCDF.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c interface.F90
gfortran  -shared definitions.o matrix.o string.o input_list.o driver.o misc.o output.o restart.o qm_out.o nuclear.o bsh.o electronic.o qm.o electronic_laser.o input.o decoherence_afssh.o decoherence_dom.o zpe.o tsh_tu.o army_ants.o pointer_basis.o  interface.o  -o ../pysharc/lib/libsharc.so -L/opt/compilers/intel/mkl/2023.0.0/lib/intel64 -lmkl_rt -lpthread -lm -lgfortran -L/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib -lhdf5 -lhdf5_hl -lmfhdf -ldf -ljpeg -L../pysharc/lib -lsharcnc -lnetcdf 
make[1]: Leaving directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
python sharc_setup build_ext --build-lib .
running build_ext




(pysharc_3.0) [root@compute source]# make
Updating "build_info.inc"
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c output.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c input.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c driver.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c interface.F90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c main.F90
gfortran     definitions.o matrix.o string.o input_list.o driver.o misc.o output.o restart.o qm_out.o nuclear.o bsh.o electronic.o qm.o electronic_laser.o input.o decoherence_afssh.o decoherence_dom.o zpe.o tsh_tu.o army_ants.o pointer_basis.o  interface.o main.o  -o  sharc2.x -L/opt/compilers/intel/mkl/2023.0.0/lib/intel64 -lmkl_rt -lpthread -lm -lgfortran -L/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib -lhdf5 -lhdf5_hl -lmfhdf -ldf -ljpeg -L../pysharc/lib -lsharcnc -lnetcdf 
/bin/ld: warning: libcrypto.so.3, needed by /opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so, not found (try using -rpath or -rpath-link)
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `EVP_sha256@OPENSSL_3.0.0'
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `HMAC@OPENSSL_3.0.0'
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `SHA256@OPENSSL_3.0.0'
collect2: error: ld returned 1 exit status
make: *** [sharc] Error 1
(pysharc_3.0) [root@compute source]# 

**But libcrypto.so.3 and libhdf5.so both are present in /opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib directory. I am not able to figure out the source of problem.**


**The modified portion of the Makefile is:**

# -------------------------------------- configure ---------------------------------------

# =======================================
#true, false     # also implies NETCDF
USE_PYSHARC := true

#intel, gnu
USE_COMPILER := gnu

#mkl,gnu
USE_LIBS := mkl

#Static libraries
COMP_STATIC := false

#needed for PYSHARC
ANACONDA := ${CONDA_PREFIX}
# =======================================

***Here I am using gnu compiler. Moreover when I compile with intel compilers, the problem is like as follow:***
(pysharc_3.0) [root@compute pysharc]# make
cd ../source; make libsharc
make[1]: Entering directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
Updating "build_info.inc"
ifort  -D__PYSHARC__  -O3 -fPIC -g   -c definitions.F90
definitions.F90(85): warning #6379: The structure contains one or more misaligned fields.   [AUX_TRAJECTORY_TYPE]
type aux_trajectory_type
-----^
definitions.F90(123): warning #6379: The structure contains one or more misaligned fields.   [TRAJECTORY_TYPE]
type trajectory_type
-----^
definitions.F90(352): warning #6379: The structure contains one or more misaligned fields.   [CTRL_TYPE]
type ctrl_type
-----^
ifort   -O3 -fPIC -g   -c matrix.f90
ifort   -O3 -fPIC -g   -c string.f90
ifort   -O3 -fPIC -g   -c input_list.f90
ifort   -O3 -fPIC -g   -c misc.f90
misc.f90(180): error #6404: This name does not have a type, and must have an explicit type.   [RAND]
      seed=int(65536*(rand()-0.5d0))
----------------------^
compilation aborted for misc.f90 (code 1)
make[1]: *** [misc.o] Error 1
make[1]: Leaving directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
make: *** [lib/libsharc.so] Error 2
(pysharc_3.0) [root@compute pysharc]# 


Kindly look into the matter, please help us to resolve both of these issues which are library problem of hdf5 (compilation with gnu compiler). Second problem is with the intel compilers which occurred during compilation

**Comment by maisebastian** [comment]
First, please use "make install" in both folders instead of just "make".
Otherwise, we will have to look further.
Best,
Sebastian

**Comment by Kalpa08** [comment]
I have done in both of the folders just now:
(pysharc_3.0) [root@compute pysharc]# make install
cd ../source; make libsharc
make[1]: Entering directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
Updating "build_info.inc"
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c definitions.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c matrix.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c string.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c input_list.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c misc.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c output.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_afssh.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c decoherence_dom.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c nuclear.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c electronic.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c qm_out.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c restart.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c qm.f90
qm.f90:3167:27:

 3167 |        do 100 jatom=1,iatom
      |                           1
Warning: Fortran 2018 deleted feature: Shared DO termination label 100 at (1)
qm.f90:3172:26:

 3172 |            do 70 jc=1,jend
      |                          1
Warning: Fortran 2018 deleted feature: Shared DO termination label 70 at (1)
qm.f90:3175:27:

 3175 |                do 50 ib=1,3
      |                           1
Warning: Fortran 2018 deleted feature: Shared DO termination label 50 at (1)
qm.f90:3178:31:

 3178 |                    do 30 jb=1,3
      |                               1
Warning: Fortran 2018 deleted feature: Shared DO termination label 30 at (1)
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c bsh.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c electronic_laser.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c input.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c zpe.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c army_ants.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c tsh_tu.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c pointer_basis.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c driver.f90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c definitions_NetCDF.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c interface.F90
gfortran  -shared definitions.o matrix.o string.o input_list.o driver.o misc.o output.o restart.o qm_out.o nuclear.o bsh.o electronic.o qm.o electronic_laser.o input.o decoherence_afssh.o decoherence_dom.o zpe.o tsh_tu.o army_ants.o pointer_basis.o  interface.o  -o ../pysharc/lib/libsharc.so -L/opt/compilers/intel/mkl/2023.0.0/lib/intel64 -lmkl_rt -lpthread -lm -lgfortran -L/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib -lhdf5 -lhdf5_hl -lmfhdf -ldf -ljpeg -L../pysharc/lib -lsharcnc -lnetcdf 
make[1]: Leaving directory `/opt/SOFTWARES/sharc/new/sharc-3.0.0/source'
python sharc_setup build_ext --build-lib .
running build_ext
cp lib/*.so ../lib
cp bin/*.py ../bin
(pysharc_3.0) [root@compute pysharc]# cd ..




(pysharc_3.0) [root@compute source]# make install
Updating "build_info.inc"
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c output.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c input.F90
gfortran    -O3 -fPIC -g  -ffree-line-length-none  -c driver.f90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c interface.F90
gfortran   -D__PYSHARC__  -O3 -fPIC -g  -ffree-line-length-none  -c main.F90
gfortran     definitions.o matrix.o string.o input_list.o driver.o misc.o output.o restart.o qm_out.o nuclear.o bsh.o electronic.o qm.o electronic_laser.o input.o decoherence_afssh.o decoherence_dom.o zpe.o tsh_tu.o army_ants.o pointer_basis.o  interface.o main.o  -o  sharc2.x -L/opt/compilers/intel/mkl/2023.0.0/lib/intel64 -lmkl_rt -lpthread -lm -lgfortran -L/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib -lhdf5 -lhdf5_hl -lmfhdf -ldf -ljpeg -L../pysharc/lib -lsharcnc -lnetcdf 
/bin/ld: warning: libcrypto.so.3, needed by /opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so, not found (try using -rpath or -rpath-link)
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `EVP_sha256@OPENSSL_3.0.0'
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `HMAC@OPENSSL_3.0.0'
/opt/SOFTWARES/anaconda/3.9/envs/pysharc_3.0/lib/libhdf5.so: undefined reference to `SHA256@OPENSSL_3.0.0'
collect2: error: ld returned 1 exit status
make: *** [sharc] Error 1
(pysharc_3.0) [root@compute source]# 

**In source directory, it's coming like this**

**Comment by markusoppel** [comment]
This is now a problem with your conda environment. I guess you are using the compilers (gfortran and gcc) from your conda installation. This is known to cause problems on "older" operation systems (you are using Centos7, right?)
I suggest to delete the compilers from your conda environment and to use the OS versions. 

One additional remark: I see that you are compiling SHARC as root. This is quite unusual. Usually, standard users will compile their own, local version of SHARC, and therefore they need a conda environment to handle the vast zoo of different versions of python and libraries. If you are root on your system, and if you are the only user of the software, you do not need a dedicated conda environment. You can simply install all necessary tools and libraries using the OS tools (yum)

**Comment by Kalpa08** [comment]
Thanks for your response. 
I am using a Centos 7 OS, using gfortran & gcc compiler to compile the software. I used anaconda environment as it was instructed in the manual. Also we have multiple users in the system.

I have been able compile it successfully using the following process mentioned in the manual:

set USE_PYSHARC to false,
run make install in source/,
run make clean in source/,
set USE_PYSHARC to true,
run make install in pysharc/.

I have redefined the MKLROOT mentioned in the line no 55 of Makefile as follow:

MKLROOT := /opt/compilers/intel/mkl/2023.0.0

Now I am running the calculations from the tutorial, generated the absorption spectrum. But the spectrum I am getting is different from the one that is given in the tutorial.
I am attaching here my files for obtained from the [calculations.](https://drive.google.com/drive/folders/10FW6u5y7N8Qxd_EYoKa1gcmIYVFprt1E?usp=share_link)

You may check the absorption spectrum I am getting [here](https://drive.google.com/file/d/1YOL8W2S3ab_KvWYAuuweR8Z5ITQRQaqr/view?usp=share_link).

**Comment by maisebastian** [comment]
Dear Kapla08,
great that you could compile pysharc now.

It is well possible that the generated absorption spectrum is different than the one in the manual. The spectrum depends on the geometries in the Wigner distribution, and the Wigner distribution depends on the random number generator used, which is from Python's random library. It is likely that you obtain different random numbers with your Python installation than we did when we generated the picture in the tutorial. This is not a reason to worry. I suggest that you simply go ahead with the tutorial.

**Comment by Kalpa08** [comment]
Dear sir
Thank you for your kind explanation and constant support during the installation. I will need your help frequently as I am learning and started working using this software. I will proceed with the tutorial if generating the spectrum is not a problem.

Can you please clarify different computers using different Python libraries produce different results like this, how can I rely on the result I get from the calculation? I may get a different result for the same problem which other people may get differently than me. Won't it will be problematic to reproduce the results?

**Comment by Kalpa08** [comment]
Dear Sir
I am again facing one new error while executing  setup_traj.py
[kalpa@compute traj]$ setup_traj.py 
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/setup_traj.py", line 1165
    print('\nPlease choose the integrator you want to use')
                                                          ^
IndentationError: unindent does not match any outer indentation level
[kalpa@compute traj]$ ls
initconds.excited  MOLCAS.RasOrb  MOLCAS.template
[kalpa@compute traj]$

**Comment by maisebastian** [comment]
Dear Kalpa08, I contacted the developer who extended setup_traj.py for the 3.0 release. As soon as we can resolve the issue, I will answer back.

**Comment by Kalpa08** [comment]
Okay sir!
Thank you
