### ISSUE TITLE
Error faced while setup_traj.py

### ISSUE THREAD

**Issue by Kalpa08** [sharc-md/sharc#48]
Dear Developers
I am following the sharc tutorial and generated the spectrum. When I am doing the "2.7 Setting up dynamics simulations"

I got the following error while executing setup_traj.py
[kalpa@compute traj]$ setup_traj.py
File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/setup_traj.py", line 1165
print('\nPlease choose the integrator you want to use')
^
IndentationError: unindent does not match any outer indentation level
[kalpa@compute traj]$ ls
initconds.excited MOLCAS.RasOrb MOLCAS.template
[kalpa@compute traj]$

Can anybody please tell me how can I overcome this problem.

**Comment by Kalpa08** [comment]
Okay sir!
Thank you

**Comment by Kalpa08** [comment]
Dear Dr. Sebastian,
Can you please let me know whether the problem got solved or not ...

**Comment by Kalpa08** [comment]
Thank you!
I have successfully run the trajectories. But while executing the trajana_nma.py, and trajana_essdyn.py I faced the following errors:


**[kalpa@compute TRAJ_00001]$ trajana_nma.py** 
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_nma.py", line 63, in <module>
    import file_handler
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/file_handler.py", line 218
    print cm.return_csv()
           ^
SyntaxError: invalid syntax

**[kalpa@compute TRAJ_00001]$ trajana_essdyn.py** 
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 47, in <module>
    import file_handler
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/file_handler.py", line 218
    print cm.return_csv()
           ^
SyntaxError: invalid syntax

**Comment by Kalpa08** [comment]
Dear Dr. Sebastian,
I am also getting error in make_fit.py as follow:
[kalpa@compute traj]$ make_fit.py
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/make_fit.py", line 52, in <module>
    import scipy.integrate as spint
ModuleNotFoundError: No module named 'scipy'
[kalpa@compute traj]$ 


Please let me know how I can fix this problem.

**Comment by maisebastian** [comment]
The two trajana scripts should now be functional. The problem was that some library files were not converted to Python 3. 
The problem with scipy seems to have been resolved by you, great!

**Comment by Kalpa08** [comment]
Dear Sebastian
I copied these library files to the lib directory and I executed trajana_essdyn.py and got the following problem related to openbabel
[kalpa@compute traj]$ trajana_essdyn.py
openbabel.py package not installed
[kalpa@compute traj]$ 


I installed openbabel 2.3.1 in the system and gave the paths in the .bashrc as follows
#openbabel
export PATH=$PATH:/opt/SOFTWARES/Openbabel/2.3.1/bin:$PATH
export LD_LIBRARY_PATH=/opt/SOFTWARES/Openbabel/2.3.1/lib:$LD_LIBRARY_PATH

still, the same problem is coming. Can you please tell me how I can solve this issue...

**Comment by maisebastian** [comment]
The error message is referring to the Python package for openbabel. I recommend that you install it through Anaconda, that should hopefully solve this issue.

**Comment by Kalpa08** [comment]
I installed it using anaconda just now and run the trajana_essdyn.py, I found the following error:

---------------------Results directory----------------------
Please give the name of the subdirectory to be used for the results (use to save similar analysis in separate subdirectories).
Name for subdirectory? [essdyn] (autocomplete enabled) 

Preparing essential dynamics analysis ...
/opt/SOFTWARES/anaconda/3.9/lib/python3.9/site-packages/openbabel/__init__.py:20: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Checking the directories...
Singlet_2//TRAJ_00004         OK
Singlet_2//TRAJ_00008         OK
Singlet_2//TRAJ_00009         OK
Singlet_3/TRAJ_00007          OK
Number of trajectories: 4
Reading trajectory Singlet_2//TRAJ_00004/output.xyz ...
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 582, in <module>
    main()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 575, in main
    ess_dyn(INFOS)
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 470, in ess_dyn
    coor_matrix = trajectory.ret_coor_matrix()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/traj_manip.py", line 107, in ret_coor_matrix
    coor_list = [structure.ret_vector() for structure in self.structures]
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/traj_manip.py", line 107, in <listcomp>
    coor_list = [structure.ret_vector() for structure in self.structures]
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/struc_linalg.py", line 76, in ret_vector
    for i in xrange(self.mol.NumAtoms()):
NameError: name 'xrange' is not defined



Can you please let me know what could be the solution to this problem...

**Comment by Kalpa08** [comment]
I checked the file /home/kalpa/.local/lib/python3.6/site-packages/openbabel/__init__.py and found the following code.
import sys
import warnings
from . import openbabel

__version__ = "3.1.0"

if "ON" == "ON":
    import os
    base_dir = os.path.abspath(os.path.dirname(__file__))
    os.environ["BABEL_LIBDIR"] = os.path.join(base_dir, "lib", "openbabel", __version__)
    os.environ["BABEL_DATADIR"] = os.path.join(base_dir, "share", "openbabel", __version__)

_thismodule = sys.modules[__name__]

class OBProxy(object):
    def __getattr__(self, name):
        if hasattr(_thismodule, name):
            return getattr(_thismodule, name)
        elif hasattr(openbabel, name):
            warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
            return getattr(openbabel, name)
        else:
            raise AttributeError

sys.modules[__name__] = OBProxy()

**Comment by Kalpa08** [comment]
**Dear Developers,
I installed the program (openbabel) using anaconda environment
following two commands were used:**
----------------------------------------------------------------------------------------------------------
conda install -c conda-forge openbabel 
conda install -c "conda-forge/label/cf202003" openbabel 
---------------------------------------------------------------------------------------------------------

[root@compute ~]# conda install -c conda-forge openbabel
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.



**Then I have run the trajana_essdyn.py script, it showed the following issue:**

Do you wish to use mass weighted coordinates? [True] 

---------Number of total steps in your trajectories---------

Number of time steps:  [1001] 

-------------The time step of your calculation--------------

Length of time step:  [0.5] 

-----------------Time steps to be analysed------------------

Please enter the time step intervals for which the statistical analysis should be carried out. 

Time step interval:  [0 1000] 

Do you want to add another time interval for analysis? [False] 

---------------------Results directory----------------------
Please give the name of the subdirectory to be used for the results (use to save similar analysis in separate subdirectories).
Name for subdirectory? [essdyn] (autocomplete enabled) 

Preparing essential dynamics analysis ...
Output directory could not be created. It either already exists or you have no writing access.
Output directory could not be created. It either already exists or you have no writing access.
/opt/SOFTWARES/anaconda/3.9/lib/python3.9/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Checking the directories...
Singlet_2//TRAJ_00004         OK
Singlet_2//TRAJ_00008         OK
Singlet_2//TRAJ_00009         OK
Singlet_3//TRAJ_00007         OK
Number of trajectories: 4
Reading trajectory Singlet_2//TRAJ_00004/output.xyz ...
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 582, in <module>
    main()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 575, in main
    ess_dyn(INFOS)
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_essdyn.py", line 470, in ess_dyn
    coor_matrix = trajectory.ret_coor_matrix()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/traj_manip.py", line 107, in ret_coor_matrix
    coor_list = [structure.ret_vector() for structure in self.structures]
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/traj_manip.py", line 107, in <listcomp>
    coor_list = [structure.ret_vector() for structure in self.structures]
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/struc_linalg.py", line 76, in ret_vector
    for i in xrange(self.mol.NumAtoms()):
NameError: name 'xrange' is not defined

**Comment by maisebastian** [comment]
Both the xrange error and the openbabel import warning should be solved now in the "main" branch (https://github.com/sharc-md/sharc/tree/main). After `conda  install -c conda-forge openbabel`, the scripts run very well for me.

**Comment by Kalpa08** [comment]
Dear Dr. Sebastian
I could not get this point. If you don't mind, could you please explain this again. I have installed openbabel using this command and getting the above error again and again. Which file I have to modify, can you please let me know about it. The problem is persistently coming to me. 
Thank you in advanced

**Comment by maisebastian** [comment]
Have you downloaded the updated scripts? You need to update all the .py files in the lib/ folder with the ones from the main branch in  https://github.com/sharc-md/sharc/tree/main

**Comment by Kalpa08** [comment]
Thanks for your response, I have just downloaded the updated scripts and I think its working now. But There is still one warning is coming mentioning : /opt/SOFTWARES/anaconda/3.9/lib/python3.9/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"

If this is not a problem I will proceed to the next step. Please let me know if there is any problem

I can see one directory as essdyn and two subdirectories as cross_av and total_cov, each containg one file
(base) [kalpa@compute essdyn]$ ls *
cross_av:
0-1000.molden

total_cov:
0-1000.molden

I after execution of trajana_essdyn.py I got the following prompts:
---------------------Results directory----------------------
Please give the name of the subdirectory to be used for the results (use to save similar analysis in separate subdirectories).
Name for subdirectory? [essdyn] (autocomplete enabled) 

Preparing essential dynamics analysis ...
Checking the directories...
Singlet_2//TRAJ_00004         OK
Singlet_2//TRAJ_00008         OK
Singlet_2//TRAJ_00009         OK
Singlet_3/TRAJ_00007          OK
Number of trajectories: 4
Reading trajectory Singlet_2//TRAJ_00004/output.xyz ...
/opt/SOFTWARES/anaconda/3.9/lib/python3.9/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Reading trajectory Singlet_2//TRAJ_00008/output.xyz ...
Reading trajectory Singlet_2//TRAJ_00009/output.xyz ...
Reading trajectory Singlet_3/TRAJ_00007/output.xyz ...
Processing data ...


Thank you

**Comment by Kalpa08** [comment]
Yes, and I also downloaded all the updated library files. should I try to start again with setup_traj.py?

**Comment by maisebastian** [comment]
No, the Python files in lib/ only affect trajana_essdyn.py and trajana_nma.py.

**Comment by Kalpa08** [comment]
**Okay but in case of trajana_nma.py, its showing error:**
(base) [kalpa@compute traj]$ trajana_nma.py 
Script for performing normal mode analysis started ...


  ================================================================================
||                                                                                ||
||                    Normal-mode analysis for SHARC dynamics                     ||
||                                                                                ||
||                      Author: Felix Plasser, Andrew Atkins                      ||
||                                                                                ||
||                                  Version:3.0                                   ||
||                                    01.04.23                                    ||
||                                                                                ||
  ================================================================================


This script reads output.xyz files, transforms into normal modes, and performs statistical analyses
(i.e., Shows you which are the most important motions).
  
-------------------Paths to trajectories--------------------

Please enter the paths to all directories containing the "TRAJ_0XXXX" directories.
E.g. Sing_2/ and Sing_3/. 
Please enter one path at a time, and type "end" to finish the list.
Path:  [end] (autocomplete enabled) Singlet_2/
['TRAJ_00004', 'TRAJ_00008', 'TRAJ_00009']
Found 3 subdirectories in total.

Path:  [end] (autocomplete enabled) Sing_3/
Does not exist or is not a directory: Sing_3/
Path:  [end] (autocomplete enabled) Singlet_3/
['TRAJ_00007']
Found 4 subdirectories in total.

Path:  [end] (autocomplete enabled) 

Total number of subdirectories: 4

------------------Path to normal mode file------------------

Please enter the path to the Molden normal mode file for your molecule. The contained geometry will be used as reference geometry.
(Atomic order must be the same as in the trajectories!)

Path:  (autocomplete enabled) ../wigner/MOLCAS.freq.molden

Do you wish to use mass weighted normal modes? [True] 

---------Number of total steps in your trajectories---------

Number of time steps:  [1001] 

-------------The time step of your calculation--------------

Length of time step:  [0.5] 

------------------Automatic plot creation-------------------

Do you want to automatically create plots of your data? [False] yes

-------------Non-totally symmetric normal modes-------------

Please enter the numbers of the normal modes (numbering as in the Molden file) whose absolute value should be considered in the analysis. Without this setting, the average for all non-totally symmetric modes should be zero. Default is to not compute the absolute. Entering -1 ends this input section.

Non-totally symmetric normal modes: [-1] (range comprehension enabled) 

--------------------Multiplication by -1--------------------
Please enter the numbers of normal modes whose values should be multiplied by -1 before statistical analysis (affects total_std.txt and cross_av_std.txt). This is only for convenience when viewing the results. Entering -1 ends this input section.

Inverted normal modes: [-1] (range comprehension enabled) 

-----------------Time steps to be analysed------------------

Please enter the time step intervals for which the statistical analysis should be carried out. 

Time step interval:  [0 1000] 

Do you want to add another time interval for analysis? [False] 

---------------------Results directory----------------------
Please give the name of the subdirectory to be used for the results (use to save similar analysis in separate subdirectories).
Name for subdirectory? [nma] (autocomplete enabled) 

Preparing NMA ...
Checking the directories...
Singlet_2//TRAJ_00004         OK
Singlet_2//TRAJ_00008         OK
Singlet_2//TRAJ_00009         OK
Singlet_3//TRAJ_00007         OK
Number of trajectories: 4
Reading trajectory Singlet_2//TRAJ_00004/output.xyz ...
Reading trajectory Singlet_2//TRAJ_00008/output.xyz ...
Reading trajectory Singlet_2//TRAJ_00009/output.xyz ...
Reading trajectory Singlet_3//TRAJ_00007/output.xyz ...
Processing data ...
Data processing finished.
Drawing plots ...
Traceback (most recent call last):
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_nma.py", line 763, in <module>
    main()
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_nma.py", line 738, in main
    nm_analysis(INFOS)
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_nma.py", line 697, in nm_analysis
    plot_summary(INFOS)
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/trajana_nma.py", line 711, in plot_summary
    plotting.mean_std_from_files(mean_file=out_dir + '/mean_against_time.txt', out_dir=out_dir + '/time_plots', xlist=[INFOS['timestep'] * i for i in range(num_steps)], std_file=out_dir + '/std_against_time.txt')
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/plotting.py", line 40, in mean_std_from_files
    mean_list += [[eval(word) for word in file_handler.line_to_words(line[:-1])]]
  File "/opt/SOFTWARES/sharc/3.0/sharc-3.0.0/bin/../lib/plotting.py", line 40, in <listcomp>
    mean_list += [[eval(word) for word in file_handler.line_to_words(line[:-1])]]
  File "<string>", line 1
    -6.877787192221402e
                      ^
SyntaxError: unexpected EOF while parsing
(base) [kalpa@compute traj]$

**Comment by Kalpa08** [comment]
Yes, sure! If possible please give an update whenever there is a change in the scripts.

**Comment by Kalpa08** [comment]
I am proceeding to the next step (ENSEMBLE MOTION PLOT), I used geo.py as mentioned in the tutorial. but its showing the error related to syntax, I am not able to figure out from where the problem is coming. Please let me know if there is any mistake from my side
(base) [kalpa@compute traj]$ cat geo.sh 
#!/bin/bash
echo "r 1 2" > Geo.inp
for i in Singlet_2/TRAJ_000*;
$SHARC/geo.py -t 0.5 -g $i/output.xyz < Geo.inp > $i/Geo.out;
done
(base) [kalpa@compute traj]$ ./geo.sh 
./geo.sh: line 4: syntax error near unexpected token `$SHARC/geo.py'
./geo.sh: line 4: `$SHARC/geo.py -t 0.5 -g $i/output.xyz < Geo.inp > $i/Geo.out;'
(base) [kalpa@compute traj]$

**Comment by maisebastian** [comment]
Indeed, there is a "do" missing after the first semicolon. The script should be:
#!/bin/bash
echo "r 1 2" > Geo.inp
for i in Singlet_2/TRAJ_000*;
do
$SHARC/geo.py -t 0.5 -g $i/output.xyz < Geo.inp > $i/Geo.out;
done

**Comment by Kalpa08** [comment]
Thank you very much. It worked for me..

**Comment by xlliu98** [comment]
Hi,
I got the same error and I found it's due to the formatting. After changing https://github.com/sharc-md/sharc/blob/5fa0f200c0747f235253dbc445d10ccfe4550fba/bin/trajana_nma.py#L665 to tm_mean.write_line([ "{:16.10f}".format(coor / cross_num_array[i]) for coor in cross_sum_array[i]]), it works fine.

**Comment by maisebastian** [comment]
Thank you xlliu98,
the changed line is now incorporated into the main branch here on Github.
Best,
Sebastian
