### ISSUE TITLE
Error with wigner.py

### ISSUE THREAD

**Issue by Yuanypu** [sharc-md/sharc#61]
Hello,

I am using sharc3.0.0, and received error while running wigner.py.
Traceback (most recent call last):
  File "/usr/local/sharc-3.0.0/bin/wigner.py", line 1524, in <module>
    main()
  File "/usr/local/sharc-3.0.0/bin/wigner.py", line 1504, in main
    ic_list = create_initial_conditions_list(amount, molecule, modes)
  File "/usr/local/sharc-3.0.0/bin/wigner.py", line 1317, in create_initial_conditions_list
    sys.stdout.write('\rProgress: [' + '=' * done + ' ' * (width - done) + '] %3i%%' % (done * 100 / width))
TypeError: can't multiply sequence by non-int of type 'float'

However, when using sharc2.1, it works smoothly.

Does anyone know what the problem is? Thanks in advance!

**Comment by rafaelpap** [comment]
I believe the problem is  solved in version 3.0.1. Line 1316 in wigner.py should be
        done = idone * width // (amount)
instead of
        done = idone * width / (amount)

**Comment by Yuanypu** [comment]
Oh, thank you for your help!
